### ISSUE TITLE
Update Tur data in infomapecology

### ISSUE THREAD

**Issue by faragec** [Ecological-Complexity-Lab/infomap_ecology_package#24]
from: https://figshare.com/articles/dataset/Data_package_from_Evaluating_the_effects_of_pollinator_mediated_interactions_using_pollen_transfer_networks_evidence_of_widespread_facilitation_in_south_Andean_plant_communities_Tur_et_al_2016_/2242447?file=3879136

Edit code when it is done.

**Comment by shainova** [comment]
done
