### ISSUE TITLE
Error in namespace preventing installation

### ISSUE THREAD

**Issue by matildabrown** [Ecological-Complexity-Lab/infomap_ecology_package#27]
Running `devtools::install_github('Ecological-Complexity-Lab/infomap_ecology_package', force=T)` generates the following error:

`Error in namespaceExport(ns, exports) : 
  undefined exports: base64_decode, base64_encode, conn_create_fd, conn_create_file, conn_create_pipepair, conn_disable_inheritance, conn_get_fileno, conn_is_incomplete, conn_read_chars, conn_read_lines, conn_set_stderr, conn_set_stdout, conn_write, curl_fds, default_pty_options, is_valid_fd, poll, process, processx_conn_close, processx_conn_is_incomplete, processx_conn_read_chars, processx_conn_read_lines, processx_conn_write, run, supervisor_kill
In addition: Warning message:
S3 methods ‘close.processx_connection’, ‘close_named_pipe.unix_named_pipe’, ‘close_named_pipe.windows_named_pipe’, ‘conditionMessage.system_command_error’, ‘conn_is_incomplete.processx_connection’, ‘conn_read_chars.processx_connection’, ‘conn_read_lines.processx_connection’, ‘conn_write.processx_connection’, ‘format.system_command_error’, ‘is_pipe_open.unix_named_pipe’, ‘is_pipe_open.windows_named_pipe’, ‘print.system_command_error’, ‘write_lines_named_pipe.unix_named_pipe’, ‘write_lines_named_pipe.windows_named_pipe’ were declared in NAMESPACE but not found `

Output from `sessionInfo()`:
`R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)`

**Comment by matildabrown** [comment]
I'm so sorry - this was an issue with my build (I think a OneDrive issue) that coincided with trying to install `infomapecology`. Please disregard!

**Comment by shainova** [comment]
Thanks for noticing that! It did seem strange...
