### ISSUE TITLE
Warning messags in the food web example

### ISSUE THREAD

**Issue by faragec** [Ecological-Complexity-Lab/infomap_ecology_package#3]
When I run:
`network_object <- create_monolayer_object(otago_links_2, directed = T, bipartite = F, node_metadata = otago_nodes_2)`

I get these warning messages:
```
[1] "Input: an unipartite edge list"
[1] 140 140
Warning: One or more rows sum to 0
Warning: One or more columns sum to 0
Joining, by = "node_name"
```

**Comment by shainova** [comment]
That's ok. It just means that some species have only incoming (e.g., top predators) or outgoing links (e.g., basal species), so the next line will result in a warning. I added the explanation to the warning message.
