### ISSUE TITLE
help - dataset ‘siberia1982_7_links’ not found

### ISSUE THREAD

**Issue by andreabisello** [Ecological-Complexity-Lab/infomap_ecology_package#30]
Hi
trying to execute this example
https://github.com/Ecological-Complexity-Lab/infomap_ecology_package/blob/master/docs/multilayer_relax.md
i obtain 
dataset ‘siberia1982_7_links’ not found
even if i execute
https://github.com/Ecological-Complexity-Lab/infomap_ecology_package/blob/master/docs/installation.md
the dataset shoult be this one
https://rdrr.io/github/Ecological-Complexity-Lab/infomap_ecology_package/man/siberia1982_7_links.html
could someome help me please?
thanks

**Comment by Geutg** [comment]
Hi,
I couldn't reproduce the issue (the command `data("siberia1982_7_links")` works smoothly).
Please try to uninstall the package and reinstall it using:
`devtools::install_github('Ecological-Complexity-Lab/infomap_ecology_package', force=T)`

Let me know if it persists.
thanks,
Geut.

**Comment by andreabisello** [comment]
@Geutg 
you are right
there is something random,
even i'm using the last version of R.
to be honest, in one pc, loading data works, but then the execution freeze with the windows loader icon executing this

```
for (r in seq(0.001,1, by = 0.0999)){
  print(r)
  modules_relax_rate <- run_infomap_multilayer(NEE2017, relax = T, silent = T, trials = 50, seed = 497294, multilayer_relax_rate = r, multilayer_relax_limit_up = 1, multilayer_relax_limit_down = 0, temporal_network = T)
  modules_relax_rate$modules$relax_rate <- r
  relaxrate_modules <- rbind(relaxrate_modules, modules_relax_rate$modules)
}

```
instead now i got this other error

> data("siberia1982_7_links")
> data("siberia1982_7_nodes")
> NEE2017 <- create_multilayer_object(extended = siberia1982_7_links, nodes = siberia1982_7_nodes, intra_output_extended = F)
> NEE2017$inter <- NULL
> relaxrate_modules <- NULL
> for (r in seq(0.001,1, by = 0.0999)){
+   print(r)
+   modules_relax_rate <- run_infomap_multilayer(NEE2017, relax = T, silent = T, trials = 50, seed = 497294, multilayer_relax_rate = r, multilayer_relax_limit_up = 1, multilayer_relax_limit_down = 0, temporal_network = T)
+   modules_relax_rate$modules$relax_rate <- r
+   relaxrate_modules <- rbind(relaxrate_modules, modules_relax_rate$modules)
+ }
[1] 0.001
Error in run_infomap_multilayer(NEE2017, relax = T, silent = T, trials = 50,  : 
  Error in Infomap stand-alone file.
> 


thanks for your help

**Comment by Geutg** [comment]
Do you have a functioning Infomap stand-alone file in the relevant folder? 
What is the output when you run `infomapecology::check_infomap()` in the R console?

If you get a `FALSE` try to install a new Infomap file by running `infomapecology::install_infomap()` in the console, then try again.

Hope it works,
Geut

**Comment by andreabisello** [comment]
thanks a lot @Geutg,
it was as your suggestion.

So,
I installed infomap.
the execution of the for-loop under windows11 64bit everything updated with latest version of R hangs-crash after some minutes or still in the loop forever (or at least more than 30 minutes)
![image](https://github.com/Ecological-Complexity-Lab/infomap_ecology_package/assets/2149815/a397281d-741b-44ae-adc9-21773d748ced)

R is doing something, because there is around 15% of cpu utilization,
but never ends.

I also tried in another gaming desktop computer, that should be powerfull, and the result is the same.

![image](https://github.com/Ecological-Complexity-Lab/infomap_ecology_package/assets/2149815/70a807cb-e773-46fa-a9b5-546ef3e2814f)

@Geutg is the script working for you?

**Comment by Geutg** [comment]
Hi, 
Yes, the script works as is should in my computer. 
it shouldn't take this long, also it should print updates from Infomap when it runs it so it might not even get there.
What version of infomapecology package are you running? 
also can you add some debug messages to see where it might stop operating as expected? 
Geut

**Comment by andreabisello** [comment]
@Geutg i'm running everything installed from the beginning in two different windows11 updated machines.
I was searching for some folder containing logs, but i'm not able to find: or it keep running endless, or R close suddendly.

**Comment by Geutg** [comment]
There are no logs as this is a code that you wrote. 
Please add print commands across your code so we know what runs and what doesn't.
also please share the version number of the infomapecology R package in your system.
Also, I see you are using an R console. Does this persist when using RStudio, or running from the commandline?

**Comment by andreabisello** [comment]
@Geutg 
Thanks for your help and your help, but at the end the team decided to move to python implementation of R so now i have no idea how is going.
