### ISSUE TITLE
Downloading Infomap for R in Windows: network analysis test

### ISSUE THREAD

**Issue by piaalexa** [Ecological-Complexity-Lab/infomap_ecology_package#4]
Hi Shai,
See attached for the error I get when I type "pip install infomap" into Windows PowerShell. I had installed miniconda Python 3 and visual studio with Workload: Desktop Development with C++. I have a Windows device so I need to use this approach to installing infomap. You had mentioned over email that this might be an issue with the Python installation. I will try to reinstall it and see if it works.

P

![Windows powershell error](https://user-images.githubusercontent.com/60489482/76902244-98a49880-6869-11ea-9ce2-5219e6482dfb.png)

**Comment by danieledler** [comment]
Hi Pia, if a reinstallation of python doesn't help making pip available on the path, you can try open _Anaconda Prompt (Anaconda 3)_ from Windows start menu. That prompt should be installed with miniconda and will create an environment where pip is recognised. From there you should be able to do `pip install infomap`. Does that work?

**Comment by danieledler** [comment]
You can also skip python and try to [download and compile Infomap from source](https://www.mapequation.org/infomap/#Download).

Or try to let the `install_infomap()` function in this repo do the job.

**Comment by piaalexa** [comment]
Hi Daniel, thanks for your reply. I managed to download infomap using python. The next step I am trying to make is to use the infomap package in R on a Windows device. I added infomap to my working directory but I still can't seem to get Rstudio to find or install the package.

**Comment by danieledler** [comment]
Is it maybe due to a naming issue, where python installs `infomap` with lower case i, and the R package assumes `Infomap` with capital I (as is generated if downloading the Infomap repo and compiling by running `make`)?

**Comment by piaalexa** [comment]
This is the error I am getting when I try install Infomap in R. It does not find it when I try library, and when I search it in packages it says it's not available for the current version (which is the most up to date one as far as I know).

![Infomap R install error](https://user-images.githubusercontent.com/60489482/76909189-90a02500-6878-11ea-9025-ebd6f4ef8590.png)

**Comment by danieledler** [comment]
I see, unfortunately Infomap is not available yet as a standalone R package which you can install with `install.packages()`. Hopefully soon, but for now you have to use the provided `install_infomap()` function in this repo (after running the lines above first). If it doesn't work, make sure you have the executable Infomap in the working directory.

**Comment by shainova** [comment]
@piaalexa If you have managed to install infomap then first you should rename it to Infomap with capital I and not i. Also put the Infomap file in the folder where your R code will be. Then, you should follow these instructions:

```R
# Install/update the packages
install.packages("attempt")
install.packages("igraph")
install.packages("bipartite")
install.packages("magrittr")
install.packages("tidyverse")
install.packages("devtools")

# Install infomapecology 
devtools::install_github('Ecological-Complexity-Lab/infomap_ecology_package', force=T)
library(infomapecology)

# Check the version. Should be 0.1.2
packageDescription('infomapecology')

# Check Infomap is running
setwd('where your Infomap file and R script now live')
check_infomap() # Make sure file can be run correctly. Should return TRUE

# Load other relevant libraries
library(attempt)
library(igraph)
library(bipartite)
library(tidyverse)
library(magrittr)
```

**Comment by piaalexa** [comment]
So far so good with Infomap installation! I will keep you posted.

![Infomap installed R1](https://user-images.githubusercontent.com/60489482/76998281-cef21e80-6922-11ea-8857-565bbdcae310.png)

**Comment by piaalexa** [comment]
I have been getting an odd error when installing packages (says I need Rtools which I do have). These packages do seem to be installed regardless, lets see if it affects data analysis.
![Uploading Infomap installed R.png…]()

**Comment by piaalexa** [comment]
![Infomap installed R](https://user-images.githubusercontent.com/60489482/76999748-25f8f300-6925-11ea-9c0c-150e665cd44f.png)

**Comment by shainova** [comment]
This problem with Rtools is not related to Infomap, so I think it will be good to fix it anyways. So I'm confused were you able to install the package and go through some of the examples to see they work?

**Comment by piaalexa** [comment]
Hi Shai, I will show you what R does when you install Infomap, and when I run the bipartite and directed foodweb script now. Summary, I was able to run the bipartite fine, and obtain the data and prepare data for the directed foodweb, but then I hit some errors that I don't understand. I'll attach some screen grabs and explain what step they are at each time. Sorry if this is just my inexperience.

**Comment by piaalexa** [comment]
Installing Infomap 1
![test 1](https://user-images.githubusercontent.com/60489482/77073173-d6660600-69bc-11ea-8742-7cdd7cabdd72.png)

**Comment by piaalexa** [comment]
Installing Infomap 2
![test 2](https://user-images.githubusercontent.com/60489482/77073232-f39ad480-69bc-11ea-9d64-c8e57ee22872.png)

**Comment by piaalexa** [comment]
Checking Infomap
![test 3](https://user-images.githubusercontent.com/60489482/77073287-090ffe80-69bd-11ea-8494-6749d31a89f0.png)

**Comment by piaalexa** [comment]
Loading and running bipartite test
![test 4](https://user-images.githubusercontent.com/60489482/77073331-1af1a180-69bd-11ea-9ab4-6d3ae3a3eb97.png)
![test bipartite](https://user-images.githubusercontent.com/60489482/77073333-1d53fb80-69bd-11ea-9140-7846577aa4c2.png)

**Comment by piaalexa** [comment]
Testing directed foodweb and heirarchial clustering

![test directed foodweb](https://user-images.githubusercontent.com/60489482/77073365-2d6bdb00-69bd-11ea-8e6f-3a7042435885.png)
![test prepare network objects](https://user-images.githubusercontent.com/60489482/77073377-30ff6200-69bd-11ea-950d-1c44697b250d.png)

**Comment by shainova** [comment]
Ok, so your installation of Infomap and infomapecology is perfect! The error you get when testing for food webs and metadata is because there is an error in the code. You should copy-paste the code from the examples in the README here in the repository. Where did you copy the code from?

**Comment by piaalexa** [comment]
Hi Shai, I was using the original script I got, but forgot to check for these changes in the the README section, sorry about that. I am getting some new errors now for otago_nodes 2, it can't find this, and the otago_nodes is showing the same error. 
![otago data error](https://user-images.githubusercontent.com/60489482/77087390-120acb00-69d1-11ea-84fc-3ccd74a02d2f.png)

**Comment by shainova** [comment]
Mmm.. this is very strange. Try some other examples see how they work maybe. If you copy-paste from the examples that should not happen.

**Comment by piaalexa** [comment]
I have been able to create the otago_nodes_2, otago_link_2, Infomap_input and infomap_objects objects after running the first part of the script again. Still getting errors when I try to do the rest of the examples on the README section. 
![otago_nodeslinks_2](https://user-images.githubusercontent.com/60489482/77130727-119d1f00-6a27-11ea-8485-c880df4c82f9.png)

**Comment by shainova** [comment]
I think this is something specific to your installation of R or related packages because for other users everything runs smoothly.  Without being there I cannot solve it. We can have a Zoom conversation and I can try to help maybe.

**Comment by piaalexa** [comment]
Thanks Shai, how about we plan for a Zoom meeting Monday or Tuesday? I will try and see if I can fix things and update you if that's the case.

**Comment by piaalexa** [comment]
Hi all, I tried again this morning and I got the rest of the README section to work. This is what I plotted from it. 
![multi-layer](https://user-images.githubusercontent.com/60489482/77327948-e564f500-6ce9-11ea-9f03-ee6febd2a799.png)

**Comment by piaalexa** [comment]
It seemed to just work after I installed the packages and made some other updates, so that's good news.

**Comment by shainova** [comment]
Great! Closing issue...
